---
title: "TITLE"
subtitle: "SUBTITLE"
author: "AUTHOR"
date: "`r format(Sys.Date(), '%d %b %Y')`"
number-sections: true
number-offset: 0
toc: true
toc-depth: 2
fig-width: 6
fig-height: 4
df-print: kable
embed-resources: true
format: 
  html: 
    highlight-style: dracula
    code-tools: true
    code-fold: show
    code-summary: "Show the code"
    code-line-numbers: true
    code-link: true # only works if code-line-numbers: false
    toc-float: true
  docx: 
    toc-title: "Table of contents"
    fig-dpi: 600
    execute:
      echo: false
knitr: 
  opts_chunk: 
    fig.path: "plots/"
    fig.keep: "all"
    dev: ['png', 'pdf']
    dev.args: 
      pdf: 
        encoding: 'WinAnsi'
        useDingbats: false
bibliography: references.bib # if using references, need a .bib file
#csl: gpl.csl # find your preferred citation style at https://www.zotero.org/styles
#css: style.css # optional html styling
crossref:
  fig-prefix: Figure
  tbl-prefix: Table
  ref-hyperlink: true
editor: source
---

# Setup

Using `r R.version.string` , @R, and ggplot2 version `r packageVersion("ggplot2")` from the tidyverse [@tidyverse].

```{r}
#| label: setup
#| message: false
# load packages

# load script files
```

# Data

```{r}
# load data

```

# Plots {#sec-plots}

@fig-example in section @sec-plots is a work of art.

## Heading 2

### Heading 3

```{r}
#| label: fig-example
#| fig-cap: Miles per gallon in city vs. highway driving for different car types.
#| fig-width: 7
#| fig-height: 5
ggplot(mpg) +
  aes(x = hwy, y = cty, color = class) +
  geom_point()
```

# Tables

My @tbl-example is even more amazing.

```{r}
#| label: tbl-example
#| tbl-cap: This is my happy table, even has a beautiful equation $x^2 - \alpha$
#| tbl-cap-location: top
mpg |> head()
```

# Equations

My favorite equation of all times is @eq-fun .

$$
\begin{aligned}
E 
  &= m \cdot c^2 \left[ 1 + \frac{1}{2} \left( \frac{v}{c} \right)^2 + 
    \frac{3}{8} \left( \frac{v}{c} \right)^4 + ... \right] \\
  &\approx m \cdot c^2
\end{aligned}
$$ {#eq-fun}

# References

::: {#refs}
:::
